name: agri_connect
description: A Flutter application connecting farmers and consumers for organic produce.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0
  flutter_svg: ^2.0.5
  shared_preferences: ^2.1.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
